name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["5.1", "5.3", "5.4", "luajit"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua ${{ matrix.lua_version }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua_version }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install busted
        run: luarocks install busted

      - name: Run tests
        run: busted
